nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <C-h> <C-w>h

filetype off
set nocompatible

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'henrik/vim-indexed-search'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'kergoth/vim-bitbake'

call vundle#end()
filetype plugin indent on

" global preferences "
colorscheme torte
set nu
set t_Co=256
set mouse=a 
set termencoding=utf-8 
set clipboard=unnamedplus

" Remember info about open buffers on close
set viminfo^=%

" Backup
set undofile
set noswapfile
set nobackup

" Sounds
set noerrorbells
set novisualbell

" search
set smartcase
set ignorecase
set incsearch
set showmatch

" indention
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" highlighting
syntax on
set hlsearch

filetype indent on

set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set laststatus=2

" autocmd vimenter * NERDTree
autocmd vimenter * nmap <C-h> <C-w>h
map <C-n> :NERDTreeToggle<CR>

" spell check
set spell spelllang=en_us

" Toggle spellchecking
function! ToggleSpellCheck()
  set spell!
  if &spell
    echo "Spellcheck ON"
  else
    echo "Spellcheck OFF"
  endif
endfunction
map <C-s> :call ToggleSpellCheck()<CR>
